name: Deploy Main

on:
  push:
    branches: [ feat/ci ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # 切换分支获取源码
      - name: Checkout # step的名称，将会在 github action 的控制台中显示
        # 选择一个action，可以理解为若干 steps.run，有利于代码复用
        uses: actions/checkout@master
      - name: Deploy on server
        run: |
          pnpm install
          pnpm run build
